name: pre-commit

on:
  push:
    branches: [ main ]
    paths:
      - "**.py"

  pull_request:
    branches: [ main ]
    paths:
      - "**.py"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pre-commit/action@v3.0.1
